server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    resolver 127.0.0.11 valid=5s ipv6=off;
    set $api_upstream api:8000;

    location /api/ {
        proxy_pass http://$api_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health/ {
        proxy_pass http://$api_upstream$request_uri;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
